/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.ResultSet; 
import java.sql.SQLException; 
import javax.swing.table.DefaultTableModel; 
import kelas.category;
/**
 *
 * @author HP
 */
public class Category extends javax.swing.JFrame {
 
    /**
     * Creates new form category
     */
    public Category() {
        initComponents();
        load_table();
    }
    
    void reset(){
        IdCategory.setText("");
        nameCategory.setText("");
    }
    
    void load_table(){ 
        DefaultTableModel model = new DefaultTableModel(); 
        model.addColumn("ID"); 
        model.addColumn("Name"); 
        try { 
            // Menggunakan class category dari package 'kelas'
            kelas.category ctg = new kelas.category(); 
            ResultSet result = ctg.TampilCategory(); 
            while (result.next()){ 
                model.addRow(new Object[]{ 
                    result.getString("CategoryId"), 
                    result.getString("CategoryName"), 
                }); 
            } 
            jTable1.setModel(model); 
        } catch (SQLException e) { 
            System.out.println("Error : " + e.getMessage()); 
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        IdCategory = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameCategory = new javax.swing.JTextField();
        tambahCategory = new javax.swing.JButton();
        ubahCategory = new javax.swing.JButton();
        hapusCategory = new javax.swing.JButton();
        resetCategory = new javax.swing.JButton();
        kembaliCategory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("ID");

        jLabel3.setText("Name");

        nameCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdCategory)
                    .addComponent(nameCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 172, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IdCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        tambahCategory.setText("Tambah");
        tambahCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahCategoryActionPerformed(evt);
            }
        });

        ubahCategory.setText("Ubah");
        ubahCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahCategoryActionPerformed(evt);
            }
        });

        hapusCategory.setText("Hapus");
        hapusCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusCategoryActionPerformed(evt);
            }
        });

        resetCategory.setText("Reset");
        resetCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCategoryActionPerformed(evt);
            }
        });

        kembaliCategory.setText("Kembali");
        kembaliCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliCategoryActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CATEGORY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambahCategory)
                        .addGap(18, 18, 18)
                        .addComponent(ubahCategory)
                        .addGap(18, 18, 18)
                        .addComponent(hapusCategory)
                        .addGap(18, 18, 18)
                        .addComponent(resetCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kembaliCategory))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahCategory)
                    .addComponent(ubahCategory)
                    .addComponent(hapusCategory)
                    .addComponent(resetCategory)
                    .addComponent(kembaliCategory))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCategoryActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_nameCategoryActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void kembaliCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliCategoryActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new dashboard().setVisible(true);
    }//GEN-LAST:event_kembaliCategoryActionPerformed

    private void resetCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCategoryActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetCategoryActionPerformed

    private void ubahCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahCategoryActionPerformed
        // TODO add your handling code here:
        try {
            kelas.category ctg = new kelas.category(); 
            ctg.setCategoryName(nameCategory.getText());
            ctg.setCategoryId(Integer.parseInt(IdCategory.getText())); 
            ctg.UbahCategory(); 
            load_table(); 
            reset();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_ubahCategoryActionPerformed

    private void tambahCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahCategoryActionPerformed
        // TODO add your handling code here:
        kelas.category ctg = new kelas.category(); 
        ctg.setCategoryName(nameCategory.getText()); 
        ctg.TambahCategory(); 
        load_table(); 
        reset();
    }//GEN-LAST:event_tambahCategoryActionPerformed

    private void hapusCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusCategoryActionPerformed
        // TODO add your handling code here:
        kelas.category ctg = new kelas.category(); 
        ctg.setCategoryId(Integer.parseInt(IdCategory.getText())); 
        ctg.HapusCategory(); 
        load_table(); 
        reset();
    }//GEN-LAST:event_hapusCategoryActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow(); 
        if (row != -1){ 
            String id = jTable1.getValueAt(row, 0).toString(); 
            String name = jTable1.getValueAt(row, 1).toString(); 
            
            IdCategory.setText(id); 
            nameCategory.setText(name); 
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new category().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdCategory;
    private javax.swing.JButton hapusCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kembaliCategory;
    private javax.swing.JTextField nameCategory;
    private javax.swing.JButton resetCategory;
    private javax.swing.JButton tambahCategory;
    private javax.swing.JButton ubahCategory;
    // End of variables declaration//GEN-END:variables
}
