/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import kelas.product;
import javax.swing.table.DefaultTableModel; 
import java.sql.ResultSet; 
import java.sql.SQLException;
import javax.swing.JOptionPane;
import tampilan.dashboard;
/**
 *
 * @author HP
 */
public class Product extends javax.swing.JFrame {

    /**
     * Creates new form product
     */
    public Product() {
        initComponents();
        load_table(); 
        reset(); 
    }
    
    void reset(){
        idProduct.setText("");
        nameProduct.setText("");
        priceProduct.setText("");
        descriptionProduct.setText("");
        comboBoxCategoryProduct.setSelectedIndex(0);
    }
    
    void load_table(){ 
        DefaultTableModel model = new DefaultTableModel(); 
        model.addColumn("ID");  
        model.addColumn("Username"); 
        model.addColumn("Category"); 
        model.addColumn("Deskripsi"); 
        model.addColumn("Price"); 
    try { 
        product prd = new product(); 
        ResultSet result = prd.TampilProduct(); 
    while (result.next()){ 
        String category = 
        (result.getInt("ProductCategory") == 1) ? "Active" : 
                "Inactive"; 
        model.addRow(new Object[]{ 
        result.getInt("ProductID"), 
        result.getString("ProductName"), category, 
        result.getString("ProductDescription"), 
        result.getInt("ProductPrice"), 
        }); 
} 
    jTable1.setModel(model); 
    } catch (SQLException e) { 
        System.out.println("Eror : " + e.getMessage()); 
        } 
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hapusProduct = new javax.swing.JButton();
        resetProduct = new javax.swing.JButton();
        kembaliProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idProduct = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameProduct = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        descriptionProduct = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        priceProduct = new javax.swing.JTextField();
        comboBoxCategoryProduct = new javax.swing.JComboBox<>();
        tambahProduct = new javax.swing.JButton();
        ubahProduct = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hapusProduct.setText("Hapus");
        hapusProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusProductActionPerformed(evt);
            }
        });
        getContentPane().add(hapusProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 12, -1, -1));

        resetProduct.setText("Reset");
        resetProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetProductActionPerformed(evt);
            }
        });
        getContentPane().add(resetProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 12, -1, -1));

        kembaliProduct.setText("Kembali");
        kembaliProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliProductActionPerformed(evt);
            }
        });
        getContentPane().add(kembaliProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 12, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PRODUCT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, 93, 28));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 53, 427, 384));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setText("ID");

        jLabel3.setText("Name");

        nameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameProductActionPerformed(evt);
            }
        });

        jLabel4.setText("Category");

        jLabel5.setText("Description");

        jLabel6.setText("Price");

        comboBoxCategoryProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        comboBoxCategoryProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCategoryProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idProduct)
                    .addComponent(nameProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(descriptionProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(priceProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(comboBoxCategoryProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(comboBoxCategoryProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(descriptionProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 53, -1, -1));

        tambahProduct.setText("Tambah");
        tambahProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahProductActionPerformed(evt);
            }
        });
        getContentPane().add(tambahProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 12, -1, -1));

        ubahProduct.setText("Ubah");
        ubahProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahProductActionPerformed(evt);
            }
        });
        getContentPane().add(ubahProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 12, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rectangle 1 (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 730, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameProductActionPerformed

    private void kembaliProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliProductActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new dashboard().setVisible(true);
    }//GEN-LAST:event_kembaliProductActionPerformed

    private void resetProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetProductActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetProductActionPerformed

    private void tambahProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahProductActionPerformed
        // TODO add your handling code here:
        try {
            kelas.product prd = new kelas.product(); 
            prd.setProductName(nameProduct.getText()); 
            prd.setProductDescription(descriptionProduct.getText()); 
            prd.setProductPrice(Integer.parseInt(priceProduct.getText())); 
            
            if (comboBoxCategoryProduct.getSelectedItem().equals("Active")) { 
                prd.setProductCategory(1); 
            } else { 
                prd.setProductCategory(0); 
            } 
            
            prd.TambahProduct(); 
            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambah");
            load_table(); 
            reset();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Tambah: " + e.getMessage());
        }
    }//GEN-LAST:event_tambahProductActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    int row = jTable1.getSelectedRow(); 
        if (row != -1){ 
            idProduct.setText(jTable1.getValueAt(row, 0).toString()); 
            nameProduct.setText(jTable1.getValueAt(row, 1).toString()); 
            String category = jTable1.getValueAt(row, 2).toString(); 
            descriptionProduct.setText(jTable1.getValueAt(row, 3).toString()); 
            priceProduct.setText(jTable1.getValueAt(row, 4).toString()); 
            
            if (category.equals("Active")){ 
                comboBoxCategoryProduct.setSelectedItem("Active"); 
            } else { 
                comboBoxCategoryProduct.setSelectedItem("Inactive"); 
            } 
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void ubahProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahProductActionPerformed
        // TODO add your handling code here:
    try {
            kelas.product prd = new kelas.product(); 
            prd.setProductId(Integer.parseInt(idProduct.getText())); 
            prd.setProductName(nameProduct.getText()); 
            prd.setProductDescription(descriptionProduct.getText()); 
            prd.setProductPrice(Integer.parseInt(priceProduct.getText())); 
            
            if (comboBoxCategoryProduct.getSelectedItem().equals("Active")) { 
                prd.setProductCategory(1); 
            } else { 
                prd.setProductCategory(0); 
            } 
            
            prd.UbahProduct(); 
            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
            load_table(); 
            reset();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Ubah: " + e.getMessage());
        }
    }//GEN-LAST:event_ubahProductActionPerformed

    private void hapusProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusProductActionPerformed
        // TODO add your handling code here:
        try {
            int confirm = JOptionPane.showConfirmDialog(this, "Yakin hapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                kelas.product prd = new kelas.product(); 
                prd.setProductId(Integer.parseInt(idProduct.getText())); 
                prd.HapusProduct(); 
                load_table(); 
                reset(); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
        }         
    }//GEN-LAST:event_hapusProductActionPerformed

    private void comboBoxCategoryProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCategoryProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCategoryProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxCategoryProduct;
    private javax.swing.JTextField descriptionProduct;
    private javax.swing.JButton hapusProduct;
    private javax.swing.JTextField idProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kembaliProduct;
    private javax.swing.JTextField nameProduct;
    private javax.swing.JTextField priceProduct;
    private javax.swing.JButton resetProduct;
    private javax.swing.JButton tambahProduct;
    private javax.swing.JButton ubahProduct;
    // End of variables declaration//GEN-END:variables
}

