/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import kelas.User; 
import javax.swing.table.DefaultTableModel; 
import java.sql.ResultSet; 
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class user extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    public user() {
        initComponents();
        load_table();
        reset();
        
    }
    
    void reset(){
        fieldUsenameUser.setText("");
        fieldEmailUser.setText("");
        fieldPasswodUser.setText("");
        fieldFullnameUser.setText("");
        comboBoxStatusUser.setSelectedIndex(0);
        fieldUsenameUser.setEditable(true);
    }
    
    void load_table(){ 
        DefaultTableModel model = new DefaultTableModel(); 
        model.addColumn("Username"); 
        model.addColumn("Email"); 
        model.addColumn("Full Name"); 
        model.addColumn("Status"); 
         
        try {
            kelas.User usr = new kelas.User(); 
            ResultSet result = usr.TampilUser(); 
            while (result.next()){ 
                String status = (result.getInt("UserStatus") == 1) ? "Active" : "Inactive"; 
                model.addRow(new Object[]{ 
                    result.getString("UserName"), 
                    result.getString("UserEmail"), 
                    result.getString("UserFullName"), 
                    status 
                }); 
            } 
            TblUser.setModel(model); 
        } catch (SQLException e) { 
            System.out.println("Error : " + e.getMessage()); 
        }
} 
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fieldUsenameUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldEmailUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldPasswodUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldFullnameUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboBoxStatusUser = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tambahUser = new javax.swing.JButton();
        ubahUser = new javax.swing.JButton();
        hapusUser = new javax.swing.JButton();
        resetUser = new javax.swing.JButton();
        kembaliUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblUser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Username");

        fieldUsenameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsenameUserActionPerformed(evt);
            }
        });

        jLabel3.setText("Email");

        jLabel4.setText("Password");

        jLabel5.setText("FullName");

        fieldFullnameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFullnameUserActionPerformed(evt);
            }
        });

        jLabel6.setText("Status");

        comboBoxStatusUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldUsenameUser)
                    .addComponent(fieldEmailUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(fieldPasswodUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(fieldFullnameUser, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(comboBoxStatusUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldUsenameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(fieldPasswodUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(fieldFullnameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(comboBoxStatusUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("USER");

        tambahUser.setText("Tambah");
        tambahUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahUserActionPerformed(evt);
            }
        });

        ubahUser.setText("Ubah");
        ubahUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahUserActionPerformed(evt);
            }
        });

        hapusUser.setText("Hapus");
        hapusUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusUserActionPerformed(evt);
            }
        });

        resetUser.setText("Reset");
        resetUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetUserActionPerformed(evt);
            }
        });

        kembaliUser.setText("Kembali");
        kembaliUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliUserActionPerformed(evt);
            }
        });

        TblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambahUser)
                        .addGap(18, 18, 18)
                        .addComponent(ubahUser)
                        .addGap(18, 18, 18)
                        .addComponent(hapusUser)
                        .addGap(18, 18, 18)
                        .addComponent(resetUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kembaliUser))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahUser)
                    .addComponent(ubahUser)
                    .addComponent(hapusUser)
                    .addComponent(resetUser)
                    .addComponent(kembaliUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldUsenameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsenameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsenameUserActionPerformed

    private void fieldFullnameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFullnameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFullnameUserActionPerformed

    private void kembaliUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliUserActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new dashboard().setVisible(true);
    }//GEN-LAST:event_kembaliUserActionPerformed

    private void resetUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetUserActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetUserActionPerformed

    private void ubahUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahUserActionPerformed
        // TODO add your handling code here:
        try {
            User usr = new User(); 
            usr.setUserName(fieldUsenameUser.getText()); 
            usr.setUserEmail(fieldEmailUser.getText()); 
            usr.setUserPassword(fieldPasswodUser.getText()); 
            usr.setUserFullName(fieldFullnameUser.getText()); 
            
            if (comboBoxStatusUser.getSelectedItem().equals("Active")) { 
                usr.setUserStatus(1); 
            } else { 
                usr.setUserStatus(0); 
            } 
            usr.UbahUser(); 
            JOptionPane.showMessageDialog(this, "User Berhasil Diubah");
            load_table(); 
            reset();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Ubah: " + e.getMessage());
        }
    }//GEN-LAST:event_ubahUserActionPerformed

    private void tambahUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahUserActionPerformed
        // TODO add your handling code here:
        try {
            User usr = new User(); 
            usr.setUserName(fieldUsenameUser.getText()); 
            usr.setUserEmail(fieldEmailUser.getText()); 
            usr.setUserPassword(fieldPasswodUser.getText()); 
            usr.setUserFullName(fieldFullnameUser.getText()); 
             
            if (comboBoxStatusUser.getSelectedItem().equals("Active")) { 
                usr.setUserStatus(1); 
            } else { 
                usr.setUserStatus(0); 
            } 
            usr.TambahUser(); 
            JOptionPane.showMessageDialog(this, "User Berhasil Ditambah");
            load_table(); 
            reset(); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Tambah: " + e.getMessage());
        } 
    }//GEN-LAST:event_tambahUserActionPerformed

    private void hapusUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusUserActionPerformed
        // TODO add your handling code here:
        try {
            int confirm = JOptionPane.showConfirmDialog(this, "Hapus user ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                kelas.User usr = new kelas.User(); 
                usr.setUserName(fieldUsenameUser.getText()); 
                usr.HapusUser(); 
                load_table(); 
                reset();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
        }
    }//GEN-LAST:event_hapusUserActionPerformed

    private void TblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblUserMouseClicked
        // TODO add your handling code here:
        int row = TblUser.getSelectedRow(); 
        if (row != -1){ 
            fieldUsenameUser.setText(TblUser.getValueAt(row, 0).toString()); 
            fieldEmailUser.setText(TblUser.getValueAt(row, 1).toString()); 
            fieldFullnameUser.setText(TblUser.getValueAt(row, 2).toString()); 
            String Status = TblUser.getValueAt(row, 3).toString(); 
             
            if (Status.equalsIgnoreCase("Active")){ 
                comboBoxStatusUser.setSelectedItem("Active"); 
            } else { 
                comboBoxStatusUser.setSelectedItem("Inactive"); 
            } 
            fieldUsenameUser.setEditable(false);
        }
    }//GEN-LAST:event_TblUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblUser;
    private javax.swing.JComboBox<String> comboBoxStatusUser;
    private javax.swing.JTextField fieldEmailUser;
    private javax.swing.JTextField fieldFullnameUser;
    private javax.swing.JTextField fieldPasswodUser;
    private javax.swing.JTextField fieldUsenameUser;
    private javax.swing.JButton hapusUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembaliUser;
    private javax.swing.JButton resetUser;
    private javax.swing.JButton tambahUser;
    private javax.swing.JButton ubahUser;
    // End of variables declaration//GEN-END:variables
}
